name: Automatic Deployment on Vercel

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Respository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip3 install -r requirements.txt

      - name: Install Vercel
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --yes